[advisories]
ignore = []


[licenses]

allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "GPL-3.0-only",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
skip = [
    { name = "hashbrown", version = "*" },
    { name = "windows-sys", version = "*" },
    { name = "windows-targets", version = "*" },
    { name = "windows_aarch64_gnullvm", version = "*" },
    { name = "windows_aarch64_msvc", version = "*" },
    { name = "windows_i686_gnu", version = "*" },
    { name = "windows_i686_gnullvm", version = "*" },
    { name = "windows_i686_msvc", version = "*" },
    { name = "windows_x86_64_gnu", version = "*" },
    { name = "windows_x86_64_gnullvm", version = "*" },
    { name = "windows_x86_64_msvc", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
